# DO NOT MAKE CHANGES TO THIS FILE.  Instead, modify
# ci/settings.yml and override what needs overridden.
# This uses spruce, so you have some options there.
---
meta:
  name:     (( param "Please name your pipeline" ))
  pipeline: (( grab meta.name ))
  target:   "am"

  git:
    email:  "<>"
    name:   "CI Bot"

  docker:
    registry: am-registry:5000
    image_prefix: (( concat meta.docker.registry "/anothermemory/" ))

  vendor:
    image: am-registry:5000/anothermemory/go-vendor
    tag:
      develop:  "develop"
      master:   "production"

  github:
    uri:          (( concat "git@github.com:" meta.github.owner "/" meta.github.repo ))
    owner:        "anothermemory"
    repo:         (( param "Please specify the name of the Github repository" ))
    private_key:  ((git_private_key))
    access_token: ((git_access_token))

resources:
- name: git-develop
  type: git
  check_every: 15s
  source:
    uri: (( grab meta.github.uri ))
    branch: develop
    private_key: (( grab meta.github.private_key ))
    paths:
      - go/base/Dockerfile

- name: git-master
  type: git
  check_every: 15s
  source:
    uri: (( grab meta.github.uri ))
    branch: master
    private_key: (( grab meta.github.private_key ))
    paths:
      - go/base/Dockerfile

- name: docker-image-go-base-develop
  type: docker-image
  check_every: 15s
  source:
    repository: (( concat meta.docker.image_prefix "go-base" ))
    tag: develop
    insecure_registries: [ (( grab meta.docker.registry )) ]

- name: docker-image-go-base-master
  type: docker-image
  check_every: 15s
  source:
    repository: (( concat meta.docker.image_prefix "go-base" ))
    tag: master
    insecure_registries: [ (( grab meta.docker.registry )) ]


jobs:
- name: build-go-base-develop
  plan:
  - { get: git-develop, trigger: true }
  - { put: docker-image-go-base-develop, params: { build: git-develop/go/base } }
- name: build-go-base-master
  plan:
  - { get: git-master, trigger: true }
  - { put: docker-image-go-base-master, params: { build: git-master/go/base } }