# DO NOT MAKE CHANGES TO THIS FILE.  Instead, modify
# ci/settings.yml and override what needs overridden.
# This uses spruce, so you have some options there.
---
meta:
  name:     (( param "Please name your pipeline" ))
  pipeline: (( grab meta.name ))
  target:   "am"

  git:
    email:  "<>"
    name:   "CI Bot"

  docker:
    registry: am-registry:5000
    image_prefix: (( concat meta.docker.registry "/anothermemory/" ))

  github:
    uri:          (( concat "git@github.com:" meta.github.owner "/" meta.github.repo ))
    owner:        "anothermemory"
    repo:         (( param "Please specify the name of the Github repository" ))
    private_key:  ((git_private_key))
    access_token: ((git_access_token))

  resource:
    git:
      base:
        type: git
        check_every: 15s
        source:
          uri: (( grab meta.github.uri ))
          private_key: (( grab meta.github.private_key ))
      go-base:
        .: (( inject meta.resource.git.base ))
        source: { branch: master, paths: ['go/base/Dockerfile']}
      git-version:
        .: (( inject meta.resource.git.base ))
        source: { branch: master, paths: ['git/gitversion/Dockerfile']}
    dockerimage:
      base:
        type: docker-image
        check_every: 15s
        source:
          tag: master
          insecure_registries: [ (( grab meta.docker.registry )) ]
      go-base:
        .: (( inject meta.resource.dockerimage.base ))
        source: { repository: (( concat meta.docker.image_prefix "go-base" )) }
      git-version:
        .: (( inject meta.resource.dockerimage.base ))
        source: { repository: (( concat meta.docker.image_prefix "git-version" )) }

resources:
- name: git-go-base-develop
  .: (( inject meta.resource.git.go-base ))
  source: { branch: develop}

- name: git-go-base-master
  .: (( inject meta.resource.git.go-base ))

- name: git-git-version-develop
  .: (( inject meta.resource.git.git-version ))
  source: { branch: develop}

- name: git-git-version-master
  .: (( inject meta.resource.git.git-version ))

- name: docker-image-go-base-develop
  .: (( inject meta.resource.dockerimage.go-base ))
  source: { tag: develop}

- name: docker-image-go-base-master
  .: (( inject meta.resource.dockerimage.go-base ))

- name: docker-image-git-gitversion-develop
  .: (( inject meta.resource.dockerimage.git-version ))
  source: { tag: develop}

- name: docker-image-git-gitversion-master
  .: (( inject meta.resource.dockerimage.git-version ))


jobs:
- name: build-go-base-develop
  serial: true
  plan:
  - { get: git-go-base-develop, trigger: true }
  - { put: docker-image-go-base-develop, params: { build: git-go-base-develop/go/base } }

- name: build-go-base-master
  serial: true
  plan:
  - { get: git-go-base-master, trigger: true }
  - { put: docker-image-go-base-master, params: { build: git-go-base-master/go/base } }

- name: build-git-gitversion-develop
  serial: true
  plan:
  - { get: git-git-version-develop, trigger: true }
  - { put: docker-image-git-gitversion-develop, params: { build: git-git-version-develop/git/gitversion } }

- name: build-git-gitversion-master
  serial: true
  plan:
  - { get: git-git-version-master, trigger: true }
  - { put: docker-image-git-gitversion-master, params: { build: git-git-version-master/git/gitversion } }